add tafsir jalalain
rioastamal/quran-json pull request #3
Opened 2019-04-29 09:04 UTC by yusufRahmatullah

raw source: https://islamkitasemua.files.wordpress.com/
PR added too on https://github.com/rioastamal/quran-text

2019-04-29 14:26 UTC, rioastamal commented
@yusufRahmatullah Terima kasih banyak telah membuat PR.

Sebelum dapat menerima PR anda, saya ingin mengkonfirmasi terlebih dahulu beberapa hal karena kesalahan dalam terjemahan dapat menyesatkan pembaca dan untuk menghindari dosa karena kita sudah berusaha untuk mencari sumber yang otentik dan kredibel.

Berikut pertanyaan saya:

1. Siapa pemilik islamkitasemua.files.wordpress.com? Apakah anda kenal secara pribadi? Dapatkah tulisannya dipertanggungjawabkan.
2. Siapakah nama penterjemah atau organisasi yang bertanggung jawab atas terjemahan tafsir Jalalain yang ada pada situs no. 1
3. Seberapa yakin anda bahwa tafsir tersebut adalah benar dan tidak mengandung kesalahan (LIhat no. 1 dan 2)
4. Saya melihat tidak ada paragraf (baris kosong pemisah e.g: misal \r\n) dalam tafsir sebuah ayat pada file tersebut sehingga akan menyulitkan pembaca jika tafsir sebuah ayat sangat panjang. Saya lebih memilih tafsir yang formatnya mudah dibaca dengan menyediakan paragraf dan baris kosong. Sebagai contoh anda dapat melihat https://quranweb.id/2/255/

```
disembah. Adapun tuhan-tuhan yang lain yang disembah oleh sebagian manusia dengan alasan yang tidak benar, memang banyak jumlahnya. Akan tetapi Tuhan yang sebenarnya hanyalah Allah. Hanya Dialah Yang hidup abadi, yang ada dengan sendiri-Nya, dan Dia pulalah yang selalu mengatur makhluk-Nya tanpa ada kelalaian sedikit pun.

Kemudian ditegaskan lagi bahwa Allah tidak pernah mengantuk. Orang yang berada dalam keadaan mengantuk tentu hilang kesadarannya, sehingga dia tidak akan dapat melakukan pekerjaannya dengan baik, padahal Allah swt senantiasa mengurus dan memelihara makhluk-Nya dengan baik, tidak pernah kehilangan kesadaran atau pun lalai.

...[CUT]...
```

Dapat anda lihat diatas bahwa setelah kata "sedikit pun" ada baris kosong.

Sekian mohon untuk dijawab.

2019-04-30 04:51 UTC, yusufRahmatullah commented
1. Sebenernya saya cari di mana2 (termasuk wikipedia) untuk tafsir jalalain yang bahasa indonesia tersedia dalam format PDF dan CHM (saya hanya ambil versi yang pdf). Menurut [website ini](https://eshaardhie.blogspot.com/2017/09/download-tafsir-jalalain-30-juz-lengkap-pdf-dan-chm-ebook-kitab-terjemah-indonesia.html), versi PDF adalah versi CHM yang dihilangkan teks arabnya, sedangkan versi CHM diterbitkan oleh pesantren Persis 91 tasikmalaya. Kurang lebih tampilannya seperti ini
![image](https://user-images.githubusercontent.com/7076830/56941313-ec1cd380-6b3d-11e9-91f2-a795870b5cdf.png)
2. Pesantren Persis 91 Kota tasikmalaya
3. Cukup yakin dilihat dari kompilasi yang dilakukan oleh Pesantren Persis
4. Akan saya coba bersihkan terlebih dahulu untuk pemisah paragrafnya

2019-05-01 17:31 UTC, rioastamal requested changes

2019-05-01 17:31 UTC, rioastamal commented on surah/1.json
> +                    "text": {},
@yusufRahmatullah Terjemahan setiap ayat harus berada pada atribut `text` bukan berdiri sendiri.

2019-05-02 02:59 UTC, yusufRahmatullah commented on surah/1.json
> +                    "text": {},
oh iya juga..

2019-09-04 04:42 UTC, closed without merging